### PR TITLE
ci: run build against PRs

### PR DESCRIPTION
**Pull request by MatyiFKBT**
# Goal
I've created a new Github Action to run against every pull request and do the following things:

- run `pnpm run build`
- capture output
- run `pnpm run compare`
- capture output
- run `pnpm run check-images`
- if the command fails, mark the check as failing

The action is using [thollander/actions-comment-pull-request](https://github.com/thollander/actions-comment-pull-request) to then create a comment with the captured output of the first two commands, like this:
img

If there's been already a comment (so the PR is updated), the bot is updating the existing comment with the latest status instead of making a new one, making it easier to see for the reviewer.

## Examples 
- MatyiFKBT/Meta/pull/3
- MatyiFKBT/Meta/pull/4

## Useful links
- https://stackoverflow.com/q/59191913/17024990
- https://github.community/t/set-output-truncates-multiline-strings/16852/2
- actions/toolkit/issues/403

<small>Merging this should close MatyiFKBT/Meta/pull/3 and MatyiFKBT/Meta/pull/4 </small>

### CODE REVIEW

**Comment by MatyiFKBT** [comment]
This currently fails to comment with the `GITHUB_TOKEN` since it's from my fork, but once merged should work.

**Review by sohcah — CHANGES_REQUESTED** [review]
3 things here:

1. `pnpm run build` is able to fail, and we should make sure that the outcome of that is checked.
2. Check Images has some useful output in the case it fails, which I believe we should display
3. I believe we could make a Markdown output for each of the commands specifically for the GitHub Action, rather than re-using the regular terminal output of each command.

**Review by sohcah — APPROVED** [review]
Looks brilliant, thanks!
I'll leave the improved markdown output for myself to work on at some point in the future, so will merge this now.

**Review by sohcah — APPROVED** [review]

**Comment by MatyiFKBT** [comment]
Yeah, the markdown output for the action runs seems a bit trickier.

Updated example: MatyiFKBT/Meta/pull/5

**Pull request merged**
